/** Shared MedLens domain vocabulary. Kept free of UI and data-access concerns. */

export const SOURCE_TYPES = [
  "USER_PROVIDED",
  "DOCUMENT_EXTRACTED",
  "AI_GENERATED",
  "HUMAN_VERIFIED",
] as const;
export type SourceType = (typeof SOURCE_TYPES)[number];

export const VERIFICATION_STATUSES = [
  "NEEDS_REVIEW",
  "HUMAN_VERIFIED",
  "UNCERTAIN",
  "REJECTED",
] as const;
export type VerificationStatus = (typeof VERIFICATION_STATUSES)[number];

export const CONFIDENCE_LEVELS = ["HIGH", "MEDIUM", "LOW", "NEEDS_VERIFICATION"] as const;
export type ConfidenceLevel = (typeof CONFIDENCE_LEVELS)[number];

/** Result status is derived only from a reference range present in the source document. */
export const RESULT_STATUSES = ["LOW", "WITHIN_STATED_RANGE", "HIGH", "UNDETERMINED"] as const;
export type ResultStatus = (typeof RESULT_STATUSES)[number];

export const PROCESSING_STATUSES = [
  "PENDING",
  "VALIDATING",
  "EXTRACTING_TEXT",
  "ANALYSING",
  "READY_FOR_REVIEW",
  "PARTIAL",
  "FAILED",
] as const;
export type ProcessingStatus = (typeof PROCESSING_STATUSES)[number];

export const INFORMATION_CATEGORIES = [
  "SYMPTOM",
  "CONDITION",
  "ALLERGY",
  "MEDICATION",
  "PROCEDURE",
  "HISTORY",
  "NOTE",
] as const;
export type InformationCategory = (typeof INFORMATION_CATEGORIES)[number];

export const sourceTypeLabel: Record<SourceType, string> = {
  USER_PROVIDED: "Provided by user",
  DOCUMENT_EXTRACTED: "Extracted from document",
  AI_GENERATED: "Generated by AI",
  HUMAN_VERIFIED: "Human verified",
};

export const verificationLabel: Record<VerificationStatus, string> = {
  NEEDS_REVIEW: "Needs review",
  HUMAN_VERIFIED: "Human verified",
  UNCERTAIN: "Marked uncertain",
  REJECTED: "Rejected",
};

export const confidenceLabel: Record<ConfidenceLevel, string> = {
  HIGH: "High extraction confidence",
  MEDIUM: "Medium extraction confidence",
  LOW: "Low extraction confidence",
  NEEDS_VERIFICATION: "Needs verification",
};

export const resultStatusLabel: Record<ResultStatus, string> = {
  LOW: "Low",
  WITHIN_STATED_RANGE: "Within stated range",
  HIGH: "High",
  UNDETERMINED: "Unable to determine",
};

export const processingStatusLabel: Record<ProcessingStatus, string> = {
  PENDING: "Queued",
  VALIDATING: "Validating document",
  EXTRACTING_TEXT: "Reading document",
  ANALYSING: "Analysing report",
  READY_FOR_REVIEW: "Ready for review",
  PARTIAL: "Partially extracted",
  FAILED: "Processing failed",
};

export const informationCategoryLabel: Record<InformationCategory, string> = {
  SYMPTOM: "Symptoms",
  CONDITION: "Conditions",
  ALLERGY: "Allergies",
  MEDICATION: "Medications",
  PROCEDURE: "Procedures",
  HISTORY: "Medical history",
  NOTE: "Notes",
};

export const NO_RANGE_TEXT = "Reference range not provided in source.";

export const GLOBAL_DISCLAIMER =
  "MedLens organizes and summarizes available medical information. It does not provide a medical diagnosis or treatment recommendation. Information should be reviewed with a qualified healthcare professional.";

export const RESPONSIBLE_AI_NOTICE =
  "MedLens helps organize and summarize medical information. It is not a diagnostic or treatment tool. AI-generated information may contain errors and should be reviewed against the original source and, where appropriate, with a qualified healthcare professional.";
